# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    class.guzzle.client: GuzzleHttp\Client

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api_http_client:
        class: AppBundle\Services\Finance\HttpClient
    yahoo_finance_csv_api:
        class: AppBundle\Services\Finance\Yahoo\CSVApi
        arguments: ['@api_http_client', 20]
    yahoo_finance_json_api:
        class: AppBundle\Services\Finance\Yahoo\JsonApi
        arguments: ['@api_http_client', 20]
    chart:
        class: AppBundle\Services\ChartService